on:
  release: 
    types: 
      - created

jobs:
  BuildImage:
    name: "Build & Publish the Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: "Build the Docker Image"
        run: docker build -t frontdoor:latest .
      - name: "Tag the Docker Image for Publishing to the ECR Repository"
        run: docker tag frontend:latest 891377095569.dkr.ecr.eu-west-1.amazonaws.com/frontdoor:latest
      - name: "Push the Docker Image to the ECR Repository"
        run: docker push 891377095569.dkr.ecr.eu-west-1.amazonaws.com/frontdoor:latest