on:
  release: 
    types: 
      - published

jobs:
  BuildImage:
    name: "Build & Publish the Docker Image"
    runs-on: ubuntu-latest
    environment:
      name: Production
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::891377095569:role/GithubActionsDeployment
          aws-region: eu-west-1
      - name: "Login to Docker"
        run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 891377095569.dkr.ecr.eu-west-1.amazonaws.com
      - name: "Build the Docker Image"
        run: docker build -t 891377095569.dkr.ecr.eu-west-1.amazonaws.com/frontdoor:latest -t 891377095569.dkr.ecr.eu-west-1.amazonaws.com/frontdoor:${{github.ref_name}} .
      - name: "Push the Release Version Tag Docker Image to the ECR Repository"
        run: docker push 891377095569.dkr.ecr.eu-west-1.amazonaws.com/frontdoor:${{github.ref_name}}
      - name: "Push the Latest Docker Tag to the ECR Repository"
        run: docker push 891377095569.dkr.ecr.eu-west-1.amazonaws.com/frontdoor:latest