on:
  release: 
    types: 
      - created

jobs:
  BuildImage:
    name: "Build & Publish the Docker Image"
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Build the Docker Image"
        run: docker build -t frontdoor:latest .
      - name: "Tag the Docker Image with the Git Tag"
        run: docker tag frontend:latest 891377095569.dkr.ecr.eu-west-1.amazonaws.com/frontdoor:${{github.ref_name}}
      - name: "Push the Release Version Tag Docker Image to the ECR Repository"
        run: docker push 891377095569.dkr.ecr.eu-west-1.amazonaws.com/frontdoor:${{github.ref_name}}
      - name: "Tag the Docker Image for Publishing to the ECR Repository"
        run: docker tag frontend:latest 891377095569.dkr.ecr.eu-west-1.amazonaws.com/frontdoor:latest
      - name: "Push the Latest Docker Tag to the ECR Repository"
        run: docker push 891377095569.dkr.ecr.eu-west-1.amazonaws.com/frontdoor:latest